{% set version = "1.12" %}

package:
  name: otpmml
  version: {{ version }}

source:
  fn: otpmml-{{ version }}.tar.gz
  url: https://github.com/openturns/otpmml/archive/v{{ version }}.tar.gz
  sha256: ce88b0d69e1a7dcb47821fbdca25b4a9830831d156407601c659cd233cafcba9

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('otpmml', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.20*
  run:
    - python
    - openturns 1.20*

test:
  imports:
    - otpmml

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Meta-modeling exchange module

extra:
  recipe-maintainers:
    - jschueller
