{% set version = "1.8" %}

package:
  name: otpmml
  version: {{ version }}

source:
  fn: otpmml-{{ version }}.tar.gz
  url: https://github.com/openturns/otpmml/archive/v{{ version }}.tar.gz
  sha256: 715f840ca39054429f00fe8500cba225b5318c7683aa8ed4bbe6def77e39a3ea

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otpmml', max_pin='x.x') }}

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns
  run:
    - python
    - openturns

test:
  imports:
    - otpmml

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER
  summary: Meta-modeling exchange module

extra:
  recipe-maintainers:
    - jschueller
