{% set version = "1.5" %}
{% set ot_version = "1.11rc1" %}

package:
  name: otpmml
  version: {{ version }}

source:
  fn: otpmml-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otpmml/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 2969078a669b2b6faf4cd3fefd1e10c5785efdecc252883d233f6cecadf991d0  # [not win]

  fn: otpmml-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otpmml-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 05e46327a59447ba81468e6f13a82a30e48103652afea3a470900a901e1f170f  # [win64 and py27]

  fn: otpmml-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otpmml-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 38e63c74809061c1dff68ebc5656ef43668a8151fb4fbc4ca22f06c70f37edce  # [win64 and py35]

  fn: otpmml-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otpmml-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: b1abcf4bae4147d982a70245fb44f7ae206f1c7d9cc3edf71fc6215c267becb2  # [win64 and py36]

build:
  number: 1

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
  run:
    - python
    - openturns

test:
  imports:
    - otpmml

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: Meta-modeling exchange module

extra:
  recipe-maintainers:
    - jschueller
