travis:
  secure:
    BINSTAR_TOKEN: DrmGKxd7kw7xzEbz99U61Kn4omZ7PvxdkBsthJxm2ltJXzL7vn9Zjix+NtpfKc4flDY1ZDMkGl7CEhu7B/sRZ/xgYQUR/ZuSObvGubq3GW2/SnvNP0Y0E2AckjYyhto4S0VKDETRAmvOXDpN6SVvDV55RTzti/YbWvBuGQQC6V8mSlZmFqHRb1n2AHShzhrRwnnScL2fHE/MdZNjV1JsIvG/5bf9YRvNhYZ1jkJkcJcqf99hAabpxWXkbK7WWmRZle801dEL9sXMVNGW58zwNy6H8qf3bfrM1awp6hf17csJ53lAwK/6v2biOzDaCu7e5GtFi3qULTO59XWPPwmwz9uygc7Uny7dQ2dfxzwReC7/G5N7Owfpd/QLzrD2L6CNZVicXpXjn0Uqml8Pu5XQGLldNnNEA0g3o2bn6/72yvWK5A3cQrzDTzwbZoL3fm0P4E+Oox+zBWFvntd2rlHQ+7OXHfd6FrrsAkww2EDZu3hOXUuSLVh84lPfebBHojIz/E8D6QarIvQBYFrcDQ9+4F9wq+5K9o5QfDSK5KoDdAdM2VNfk6xGVGX8ToEy+tpZIPXmeBVkMp/WvJjUtvVNB18Z4ioe7MrJJJFZ7SMUQ+9ZDiUdv7Pub8XlAVgpf3B65PijJEpl+vL5LATso+tO9ezTFokmAoT2QyniYde/ub4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
