travis:
  secure:
    BINSTAR_TOKEN: nxICa8W2wTORxDVesCIhRUWwKq5NTKXKCb/0DF2AnrHycAM9YciupQCMqDs9LNaYIDJLPeEUeH1uH/sxELmbqulLMvn0+Bt4ACAu6xTg2N/XS/P+1PrNyX/shtARKVD9qaxS+KAVy7IUBsNXs8K7WShKDwZ+eWuL7wDKFQFcPmTb5sKra5zVQiBLu0AQ9V9cqdQeUCUIMTGtxGRfcG+aOFerpamdyikNRxMr+K/pyJz7kKsTujYfx//K1MeeYLIGizS67/Vi5D9n6DUW0cW6F/HLjkjNo3LvRAdMfYvuNI0OIS0XgWjh/qeW4AGiAtVFJzvCmdIgDyRkb4MS1CajURu5BzcvvQNhzbux/D/FE2lR0XZZMjvYAqruollgUUcsfSCcDeO/Hc1WPVnDFBWkBmHcH1JIGK9SlE/DgZ0He768XbnZbwmYed18UgU5+nP6BwMWgkEjqSk6lFLebI/hex8yVEHHPj0rDQWg+rpy1mWOBb3sZpDMGbR+QYN9v8m+PehwnDORP17puF+IcJ88QQ6beXNpmUg7fL4ZeQf4GOAct1/HIZhe8sps23qrMPJgfBlsLtzHIya1PBVtdIN+bRB6o63vR7AdqyLkM9mMm95qW+qnem5eXH9PEZRW/fZ8553rfYoK+C5vZsQjn4TjbCyiCjQwzVoGKetyYO8m5uw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
