travis:
  secure:
    BINSTAR_TOKEN: BlpxNL2XqRnkz9waOpMoDdAwyinUjhWUlExGB+6e17F8v13GidznSt+p+0lRRgXUKGSgBZ/y0RvY74TsP7ogXlVRxNTjYQSGbYN3BKeyBEn9ZSkyZDJAPnsGnQ2so9vlsthXukPjJnKZDR4efhDsBI1mz9/8m2e/xVqmQPrSaPwUr2EsFi7emc47xn3RdzppRC/VCjz0Wi74Xq4bcI1JX13GRNffx1tRTG7IVXe6QXLJaJHqCmVs3Q+uqG1xEmf6+SxydQlZsmoJxfcBAabpOSeX7S3ytN1lq3sk81Ia1dmz16MXlgE7sw/TAitwbM4CGcvldCBXXcFK7/uidvC8ebwBNID4dwyfoPhazFwqHP8KhUlDLpvEw7y6yGsASs1Zio6KT0j0vM+h/yUQCseKHNMUjjiubAB7d+KW2km5DZZXKbQX/immZdfJoZqp+yAzvqSD3U1aEz7WN3ojUmDYYN0XP6p1Oov/pv7rxSyDJlzmUrkuRjdVyy57Ov+N/fKgt4LHQV3yc37+5qrm47rIjRmMIJGu2D/jiCZVkmN/qDBH8fobW9k9Oj4XRaoSB8AckGtEb5ilIVXCU/uQnVnMhzS04m10hGxlC9A7YhpH5WOLll0rqMhwiA0Zw9O7Dmc667oiAgwjozlzmp7nWSTMl5ZhniEhwvr1gQWorc201c0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
