appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: rBrWkCq4DN4dA/zU88z1zgkV685GQderVwEtdKa5htk35IIeFW7pgnKfXKV9fx4JnebOUBbJnS0dzvd919IMsH190r3XXYIwIYAYmuLimhpi5yHz3VqtBK5nguYGf7bncI9e7KVrSvSYo2oXZcWX7QpytaQhgYokNcKGBAjbmKX+93bV8A2c55504N6nCvach4yMHvYe55dbxnp16i3cDPXqykM05wm4uuZIF71XNJYkLZZ3a+NRogFeVnnENCzw3uMox/dbn5VYbNjuBzgcbCBI8NnNv51zW+CLnVqb29FvKZX8CJiO9trmnRyGOGlZXBA8EHPK1ko0Gi2+RuBZ9KlLYhYflYoFABn08S03Fb/CrhfnUXFRXXS416QfeIAZ0eamqVJl0aQ9aoHskfDRAUMsqC1rjmgd34Dnuj9Ft7W1AUzUCijwxXi+PCp/hwsaMkxEOKLNsh0bNTE9Th84zbPF9jdB+Bu2uB8Mjl1dOxEtBNo1lPJyBhBblIiufhdKpas4JdxyFKngHkA+PzhmeDGKshLqswmjUqsYEutnAVi+YTIQSFkeREMAzNxhFgzxmbMNBqLEpTrN8bQiBLLdykaaWh+H6FnWBIwQdtE57EaWTSIQsSJmWmjy84pQ3g61vgApVePVwpXC9n53rMcaZk0xFvg5p0sNB8Qf28OeSKg=}
provider:
  win: azure
conda_forge_output_validation: true
